### ISSUE TITLE
Exporting Policies fails

### ISSUE THREAD

**Issue by sethbeauchamp** [CiscoDevNet/python-viptela#38]
Using an ubuntu docker container and a fresh install via 'pip3 install viptela' policies are failing to export.

root@b0cfad95d198:/# vmanage --host 10.10.20.90 --username admin --password admin export policies --file 19-2-1-policy.json 
Exporting policies to 19-2-1-policy.json
Traceback (most recent call last):
  File "/usr/local/bin/vmanage", line 11, in <module>
    sys.exit(vmanage())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/vmanage/cli/export/policies.py", line 19, in policies
    vmanage_files.export_policy_to_file(export_file)
  File "/usr/local/lib/python3.6/dist-packages/vmanage/apps/files.py", line 162, in export_policy_to_file
    local_policies_list = local_policy.get_local_policy_list()
  File "/usr/local/lib/python3.6/dist-packages/vmanage/api/local_policy.py", line 102, in get_local_policy_list
    self.convert_definition_id_to_name(policy['policyDefinition'])
AttributeError: 'LocalPolicy' object has no attribute 'convert_definition_id_to_name'

**Comment by stevenca** [comment]
Easy fix.  Should have the PR by the end of the week.

**Comment by stevenca** [comment]
We'll push an update to pypi by the end of the week, but can you install from the repo and let me know if this resolves your issue?

**Comment by sethbeauchamp** [comment]
Looks like this has corrected the issue. Thanks!
