### ISSUE TITLE
404 Error when exporting policies - multiple definitions types incompatible with vManage 19.2.2

### ISSUE THREAD

**Issue by sethbeauchamp** [CiscoDevNet/python-viptela#59]
One of the URLs is giving a 404 error. Should be an easy fix, I tried looking at the API docs to find the correct url, but was not sure what this was trying to access specifically. I ran this against a vManage running 19.2.2. Using code labeled "0.3.0"

`(sdwan-viptela-0.3.0) Seths-MacBook-Pro:sdwan-viptela-0.3.0 seth$ vmanage --host vmanage.viptela.net --username admin --password goodpass export policies --file vManage-192-policies.json
Exporting policies to vManage-192-policies.json
Traceback (most recent call last):
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/bin/vmanage", line 33, in <module>
    sys.exit(load_entry_point('viptela', 'console_scripts', 'vmanage')())
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/cli/export/policies.py", line 19, in policies
    vmanage_files.export_policy_to_file(export_file)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/apps/files.py", line 190, in export_policy_to_file
    policy_definitions_list = self.policy_data.export_policy_definition_list()
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/data/policy_data.py", line 328, in export_policy_definition_list
    policy_definition_list = self.policy_definitions.get_policy_definition_list(definition_type)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/api/policy_definitions.py", line 120, in get_policy_definition_list
    definition_list = self.get_policy_definition_list(def_type)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/api/policy_definitions.py", line 131, in get_policy_definition_list
    response = HttpMethods(self.session, url).request('GET')
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/api/http_methods.py", line 114, in request
    raise Exception(f"{self.url}: Error {result['status_code']} ({result['status']})")
Exception: https://vmanage-1275533.viptela.net:443/dataservice/template/policy/definition/deviceaccesspolicy: Error 404 (not_found)`

**Comment by sethbeauchamp** [comment]
the following items do not appear to be valid in vmanage 19.2.2

"deviceaccesspolicy", "deviceaccesspolicyv6", "ssldecryption", "fxoport", "fxsport", "dialpeer", "srstphoneprofile"

**Comment by jmstudyacc** [comment]
Hi - I also received this error message today when attempting to collect policies off a 19.2.2 vManage.

Anything I can do to help? Is it known if this issue is not present in later versions of vManage?
