### ISSUE TITLE
Not updating existing templates

### ISSUE THREAD

**Issue by stevenca** [CiscoDevNet/python-viptela#6]
(python-viptela) STEVENCA-M-C6HA:python-viptela stevenca$ vmanage --host=192.133.178.167 import templates --file=branch-4331.json --update
Importing templates from branch-4331.json
Traceback (most recent call last):
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/bin/vmanage", line 10, in <module>
    sys.exit(main())
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/vmanage/cli/import_cmd/templates.py", line 25, in templates
    result = vmanage_session.import_templates_from_file(file, update=update, check_mode=check, name_list = name, type = type)
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/vmanage/api.py", line 430, in import_templates_from_file
    self.add_feature_template(feature_template)
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/vmanage/api.py", line 481, in add_feature_template
    return self.request('/template/feature/', method='POST', data=json.dumps(payload))
  File "/Users/stevenca/Workspaces/python-viptela/python-viptela/lib/python3.7/site-packages/vmanage/api.py", line 122, in request
    raise Exception('{0}: {1}'.format(error, details))
Exception: Failed to create template: Template with name 'system' already exists

**Comment by mtarking** [comment]
@stevenca was ```branch-4331.json``` a device template?
