### ISSUE TITLE
Key Errors in policy_data.py

### ISSUE THREAD

**Issue by sethbeauchamp** [CiscoDevNet/python-viptela#60]
I came across the two key errors below, I have included a change I made that fixed it however I will leave it up to someone more familiar with the project to make proper corrections.

**First**

`
(sdwan-viptela-0.3.0) Seths-MacBook-Pro:sdwan-viptela-0.3.0 seth$ vmanage --host vmanage.viptela.net --username admin --password goodpass export policies --file vManage-192-policies.json
Exporting policies to vManage-192-policies.json
Traceback (most recent call last):
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/bin/vmanage", line 33, in <module>
    sys.exit(load_entry_point('viptela', 'console_scripts', 'vmanage')())
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/cli/export/policies.py", line 19, in policies
    vmanage_files.export_policy_to_file(export_file)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/apps/files.py", line 190, in export_policy_to_file
    policy_definitions_list = self.policy_data.export_policy_definition_list()
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/data/policy_data.py", line 331, in export_policy_definition_list
    definition_detail = self.policy_definitions.get_policy_definition(policy_definition['type'],
KeyError: 'type'
`
fix:
line 332 in policy_data.py
           definition_detail = self.policy_definitions.get_policy_definition(policy_definition['data'][0]['type'],
                                                                             policy_definition['data'][0]['definitionId'])

**Second**

`
sdwan-viptela-0.3.0) Seths-MacBook-Pro:sdwan-viptela-0.3.0 seth$ vmanage --host vmanage.viptela.net --username admin --password goodpass export policies --file vManage-192-policies.json
Traceback (most recent call last):
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/bin/vmanage", line 33, in <module>
    sys.exit(load_entry_point('viptela', 'console_scripts', 'vmanage')())
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/cli/export/policies.py", line 19, in policies
    vmanage_files.export_policy_to_file(export_file)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/apps/files.py", line 191, in export_policy_to_file
    central_policies_list = self.policy_data.export_central_policy_list()
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/data/policy_data.py", line 499, in export_central_policy_list
    converted_policy_definition = self.convert_policy_to_name(central_policy)
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/data/policy_data.py", line 408, in convert_policy_to_name
    self.convert_definition_id_to_name(converted_policy_item['policyDefinition'])
  File "/Users/seth/dev-projects/sdwan-viptela-0.3.0/vmanage/data/policy_data.py", line 251, in convert_definition_id_to_name
    assembly_item['definitionName'] = policy_definition_detail['name']
KeyError: 'name'
`

fix:
line 250
    assembly_item['definitionName'] = policy_definition_detail['data'][0]['name']

**Comment by radtrentasei** [comment]
I believe these have been fixed in current release, can you confirm?
